language: julia
os:
  - linux
  - osx
julia:
  - 0.6
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("Cards")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("Cards")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
