language: julia
julia:
  - 0.6
matrix:
  include:
    - os: linux
      sudo: required  # Gtk needs to apt-get install
      before_script:  # Using xvfb to run tests that require a GUI
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        - sleep 3 # give xvfb some time to start
    - os: osx
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("WaveSim")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("WaveSim")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
